# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeeingSound' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ColorsSpotify
  pod 'Alamofire', '~> 5.0.0-beta.3'

  pod 'SwiftyJSON', :git =>'https://github.com/SwiftyJSON/SwiftyJSON.git'

end
